name: Rust

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS

        strategy:
            matrix:
                os: [macOS-latest, windows-latest, ubuntu-latest]

        steps:
            - name: Setup repo
              uses: actions/checkout@v2

            - name: Build
              run: cargo build --verbose

            - name: Run tests
              run: cargo test --verbose
