name: Rust

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

env:
    CARGO_TERM_COLOR: always

jobs:
    test_x86:
        name: Test x86
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macOS-latest, windows-latest, ubuntu-latest]

        steps:
            - name: Setup repo
              uses: actions/checkout@v2

            - name: Build
              run: cargo build --verbose

            - name: Test
              run: cargo test --verbose

    test_other:
        name: Test Arm
        runs-on: ubuntu-latest

        strategy:
            matrix:
                target:
                    - armv7-unknown-linux-gnueabihf

        steps:
            - name: Setup repo
              uses: actions/checkout@v2

            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  target: ${{ matrix.target }}
                  override: true

            - uses: actions-rs/cargo@v1
              with:
                  use-cross: true
                  command: build
                  args: --release --target=${{ matrix.target }}

            - uses: actions-rs/cargo@v1
              with:
                  use-cross: true
                  command: test
                  args: --target=${{ matrix.target }}
